<?php
namespace Mage2\ArgumentsReplacement\Command;

use Mage2\ArgumentsReplacement\Model\Device;
use Mage2\ArgumentsReplacement\Model\DeviceInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Index extends Command
{
    /**
     * @var Device
     */
    protected $device;

    /**
     * Index constructor.
     * @param DeviceInterface $device
     */
    public function __construct(DeviceInterface $device)
    {
        $this->device = $device;
        parent::__construct();
    }

    /**
     * Configuration method
     *
     * @return $this
     */
    protected function configure()
    {
        $this->setName('mage2:argument-replace');
        $this->setDescription('Magento2 arguments replacement');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     *
     * @return string
     */
    public function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln($this->device->getDevicesList());
    }
}