<?php
namespace Mage2\VirtualTypes\Command;

use Mage2\VirtualTypes\Model\DeviceInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Index extends Command
{
    /**
     * @var DeviceInterface
     */
    protected $device;

    /**
     * Index constructor.
     * @param DeviceInterface $device
     */
    public function __construct(DeviceInterface $device)
    {
        $this->device = $device;
        parent::__construct();
    }

    /**
     * Configuration method
     *
     * @return $this
     */
    protected function configure()
    {
        $this->setName('mage2:virtual-types');
        $this->setDescription('Magento2 object manager virtual types');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     *
     * @return array
     */
    public function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln($this->device->getDevicesList());
    }

}