<?php
namespace Mage2\Magento2Assets\Block;

use Magento\Framework\View\Element\Template;

class Main extends Template
{
    /**
     * @return $this
     */
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}