<?php
namespace Mage2\HelloMagento2Cmd\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Index extends Command
{
    public function __construct()
    {
        parent::__construct();
    }

    protected function configure()
    {
        $this->setName('mage2:hello-magento2');
        $this->setDescription('Hello Magento 2 test description');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Hello Magento2 Cmd');
    }
}