<?php
namespace Mage2\HelloMagento2Admin\Block\Adminhtml;

use Magento\Backend\Block\Template;

class Main extends Template
{
    /**
     * @return $this
     */
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}